services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    container_name: gestorservicios
    depends_on:
      - database
    restart: unless-stopped
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-gestordeprojectos.local}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|gestordeprojectos.local}|php$$}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-gestordeprojectos.local}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      
    
#    ports:
#      # HTTP
#      - target: 80
#        published: 8081
#        protocol: tcp
#      # HTTPS
#      - target: 443
#        published: 4431
#        protocol: tcp
#      # HTTP/3
#      - target: 443
#        published: 4431
#        protocol: udp    
           
    labels:
      - traefik.enable=true
      # Route for API docs
      - traefik.http.routers.gestor-proyectos-api.rule=Host(`gestordeprojectos.local`)
      - traefik.http.routers.gestor-proyectos-api.entrypoints=web
      
      
      - traefik.http.routers.gestor-proyectos-api-secure.rule=Host(`gestordeprojectos.local`)
      - traefik.http.routers.gestor-proyectos-api-secure.entrypoints=websecure
      - traefik.http.routers.gestor-proyectos-api-secure.tls=true

    networks:
      - frontend
#      - internal

  pwa:
    image: ${IMAGES_PREFIX:-}app-pwa
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://php
    networks:
      - frontend
#      - internal
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.gestor-proyectos-pwa.rule=Host(`admin.gestordeprojectos.local`)
      - traefik.http.routers.gestor-proyectos-pwa.entrypoints=web

      - traefik.http.routers.gestor-proyectos-secure-pwa.tls=true
      - traefik.http.routers.gestor-proyectos-secure-pwa.entrypoints=websecure
      - traefik.http.routers.gestor-proyectos-secure-pwa.rule=Host(`admin.gestordeprojectos.local`)

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
#      - internal
      - frontend

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
  database_data:

networks:
  frontend:
    external: true
#  internal:
#    driver: bridge
